<?php

/**
 * Implements HOOK_enable().
 */
function conditional_assets_enable() {
  drupal_rebuild_theme_registry();
}

/**
 * Implements HOOK_theme().
 * When the theme registry is rebuilt, we also build the conditional stylesheets.
 */
function conditional_assets_theme($existing, $type, $theme, $path) {
  // Process the conditional stylesheets for every active theme.
  $themes = list_themes();
  foreach (array_keys($themes) as $theme) {
    // We only need to process active themes.
    if ($themes[$theme]->status) {
      $paths = conditional_assets_paths_to_basetheme($theme);
      conditional_assets_styles($paths);
      conditional_assets_scripts($paths);
    }
  }

  // Return nothing.
  return array();
}

/**
 * Implements MODULE_preprocess_page().
 */
function conditional_assets_preprocess_page(&$vars) {
  // Append them to $styles and add a $conditional_assets variable.
  $vars['styles'] .= $vars['conditional_assets_styles'] = variable_get('conditional_assets_styles_'. $GLOBALS['theme'], '');
  $vars['scripts'] .= $vars['conditional_assets_scripts'] = variable_get('conditional_assets_scripts_'. $GLOBALS['theme'], '');
}

/**
 * Implements MODULE_preprocess_maintenance_page().
 */
function conditional_assets_preprocess_maintenance_page(&$vars) {
  // Append them to $styles and add a $conditional_assets variable.
  $vars['styles'] .= $vars['conditional_assets_styles'] = variable_get('conditional_assets_styles_'. $GLOBALS['theme'], '');
  $vars['scripts'] .= $vars['conditional_assets_scripts'] = variable_get('conditional_assets_scripts_'. $GLOBALS['theme'], '');
}

/**
 * Return paths for the theme and its base themes.
 *
 * @param $theme
 *   The name of the theme.
 * @return
 *   An array of all the theme paths.
 */
function conditional_assets_paths_to_basetheme($theme) {
  static $theme_paths;
  if (empty($theme_paths[$theme])) {
    $theme_paths[$theme] = array();
    $themes = list_themes();
    // Grab the paths from the base theme.
    if (!empty($themes[$theme]->base_theme)) {
      $theme_paths[$theme] = conditional_assets_paths_to_basetheme($themes[$theme]->base_theme);
    }
    $theme_paths[$theme][$theme] = dirname($themes[$theme]->filename);
  }
  return $theme_paths[$theme];
}

function conditional_assets_styles($paths) {
  global $language;
  $themes = list_themes();
  // Grab all the conditional stylesheets.
  $stylesheets = array();
  // Start with the base theme and travel up the chain to the active theme.
  foreach ($paths as $theme_name => $path) {
    // Look at the conditional-stylesheets defined in the theme's .info file.
    if (!empty($themes[$theme_name]->info['conditional-stylesheets'])) {
      foreach ($themes[$theme_name]->info['conditional-stylesheets'] as $condition => $css) {
        // Allow the theme to override its base themes' styles.
        foreach ($css as $media => $files) {
          foreach ($files as $file) {
            $stylesheets[$condition][$media][$file] = $path;
          }
        }
      }
    }
  }
  // Render the stylesheets to link elements.
  $conditional_assets_styles = '';
  if (!empty($stylesheets)) {
    $query_string = '?'. substr(variable_get('css_js_query_string', '0'), 0, 1);
    $base_path = base_path();
    // Support for scaffold module.
    if (module_exists('scaffold')) {
      $base_path .= 'scaffold/';
    }
    foreach ($stylesheets as $condition => $css) {
      // Each condition requires its own set of links.
      $output = '';
      foreach ($css as $media => $files) {
        foreach ($files as $file => $path) {
          // Don't allow non-existent stylesheets to clutter the logs with 404.
          if (file_exists("./$path/$file")) {
            $output .= "<link type=\"text/css\" rel=\"stylesheet\" media=\"$media\" href=\"$base_path$path/$file$query_string\" />\n";
            if ($language->direction == LANGUAGE_RTL){
              $file_rtl = str_replace('.css', '-rtl.css', $file);
              if (file_exists("./$path/$file_rtl")) {
                $output .= "<link type=\"text/css\" rel=\"stylesheet\" media=\"$media\" href=\"$base_path$path/$file_rtl$query_string\" />\n";
              }
            }
          }
        }
      }
      if ($output) {
        // When targeting non-IE browsers.
        if (stristr($condition, '!IE') !== FALSE) {
          $conditional_assets_styles .= "<!--[$condition]><!-->\n$output<!--<![endif]-->\n";
        }
        else {
          $conditional_assets_styles .= "<!--[$condition]>\n$output<![endif]-->\n";
        }
      }
    }
  }
  // Save the stylesheets for later retrieval.
  if ($conditional_assets_styles) {
    variable_set('conditional_assets_styles_' . $theme_name, $conditional_assets_styles);
  }
  else {
    variable_del('conditional_assets_styles_' . $theme_name);
  }
}

function conditional_assets_scripts($paths) {
  $themes = list_themes();
  // Grab all the conditional scripts.
  $scripts = array();
  // Start with the base theme and travel up the chain to the active theme.
  foreach ($paths as $theme_name => $path) {
    // Look at the conditional-scripts defined in the theme's .info file.
    if (!empty($themes[$theme_name]->info['conditional-scripts'])) {
      foreach ($themes[$theme_name]->info['conditional-scripts'] as $condition => $js) {
        // Allow the theme to override its base themes' scripts.
        
        foreach ($js as $key => $file) {
          $scripts[$condition][$file] = $path;
        }
      }
    }
  }
  // Render the scripts to link elements.
  $conditional_assets_scripts = '';
  if (!empty($scripts)) {
    $query_string = '?'. substr(variable_get('css_js_query_string', '0'), 0, 1);
    $base_path = base_path();
    foreach ($scripts as $condition => $js) {
      // Each condition requires its own set of links.
      $output = '';
      foreach ($js as $file => $path) {
        if (file_exists("./$path/$file")) {
          $output .= "<script type=\"text/javascript\" src=\"$base_path$path/$file$query_string\"></script>\n";
        }
      }
      if ($output) {
        // When targeting non-IE browsers.
        if (stristr($condition, '!IE') !== FALSE) {
          $conditional_assets_scripts .= "<!--[$condition]><!-->\n$output<!--<![endif]-->\n";
        }
        else {
          $conditional_assets_scripts .= "<!--[$condition]>\n$output<![endif]-->\n";
        }
      }
    }
  }
  // Save the scripts for later retrieval.
  if ($conditional_assets_scripts) {
    variable_set('conditional_assets_scripts_'. $theme_name, $conditional_assets_scripts);
  }
  else {
    variable_del('conditional_assets_scripts_'. $theme_name);
  }
}
