<?php

/* --- HOOKS ---------------------------------------------------------------- */

/**
 * Implementation of hook_menu().
 */
function html_test_menu() {
  $items = array();
  $items['html-test'] = array(
    'title' => 'HTML test',
    'page callback' => 'html_test_page',
    'access arguments' => array('access html test page'),
    'type' => MENU_CALLBACK,
    'file' => 'elements.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function html_test_perm() {
  return array('access html test page');
}
