<?php
// $Id: sitedir_migrate.module,v 1.3 2009/12/29 18:33:23 andrewmriley Exp $

function sitedir_migrate_menu() {
  $items['admin/settings/sitedir_migrate'] = array(
    'title' => 'Site Directory Migrate',
    'description' => 'Allows you to migrate the directory name in /sites to a different directory name',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sitedir_migrate_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/sitedir_migrate/confirm'] = array(
    'title' => 'Run Migration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sitedir_migrate_settings_submit_confirm'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function sitedir_migrate_init() {
  drupal_set_message("The site directory migrate module is currently enabled, unless you are doing the migration right now, there's no reason to leave it enabled.", 'warning', FALSE);
}

function sitedir_migrate_settings() {
  $form['sitedir_migrate_from'] = array(
    '#type' => 'textfield',
    '#title' => t('From'),
    '#description' => t('Enter the directory name you are moving from.  DO NOT include the beginning or ending slashes.  DO NOT include /sites'),
    '#default_value' => variable_get('sitedir_migrate_from', NULL),
  );
  $form['sitedir_migrate_to'] = array(
    '#type' => 'textfield',
    '#title' => t('To'),
    '#description' => t('Enter the directory name you are moving to.  DO NOT include the beginning or ending slashes.  DO NOT include /sites'),
    '#default_value' => variable_get('sitedir_migrate_to', NULL),
  );
  $form['#submit'] = array('sitedir_migrate_settings_submit');
  return system_settings_form($form);
}

function sitedir_migrate_settings_validate($form, $form_state) {
  if (empty($form_state['values']['sitedir_migrate_from'])) {
    form_set_error('sitedir_migrate_from', t('Please fill out the From field'));
  }
  if (empty($form_state['values']['sitedir_migrate_to'])) {
    form_set_error('sitedir_migrate_to', t('Please fill out the To field'));
  }
}

function sitedir_migrate_settings_submit($form, &$form_state) {
  variable_set('sitedir_migrate_from', $form_state['values']['sitedir_migrate_from']);
  variable_set('sitedir_migrate_to', $form_state['values']['sitedir_migrate_to']);
  drupal_goto('admin/settings/sitedir_migrate/confirm');
}

function sitedir_migrate_settings_submit_confirm() {
  $results = module_invoke_all('sitedir_query');
  $results = join(', ', $results);
  return confirm_form($form, 'Are you sure you want to migrate your site directory?', 'admin/settings/sitedir_migrate', 'The following features will be migrated: ' . $results, t('Migrate it'));
}

function sitedir_migrate_settings_submit_confirm_submit($form, &$form_state) {
  $from = 'sites/' . variable_get('sitedir_migrate_from', NULL);
  $to = 'sites/' . variable_get('sitedir_migrate_to', NULL);
  module_invoke_all('sitedir_update', $from, $to);
  cache_clear_all();
  drupal_set_message("The site directory migration is complete.  Please don't forget to " . l('change your file path manually', 'admin/settings/file-system') . '.', 'notice');
  watchdog('Sitedir Migrate', 'Migration complete');
  $form_state['redirect'] = 'admin/settings/sitedir_migrate';
}