<?php
// $Id: semantic_cck.module,v 1.3.2.6 2010/09/26 08:51:26 rjay Exp $

function _semantic_cck_setting_names() {
  $setting_names = array('semantic_cck_field_element', 'semantic_cck_field_class',
    'semantic_cck_label_element_above', 'semantic_cck_label_class_above',
    'semantic_cck_label_class_inline','semantic_cck_label_suffix_above',
    'semantic_cck_label_suffix_inline', 'semantic_cck_label_element_inline',
    'semantic_cck_multiple_items_element', 'semantic_cck_multiple_items_class',
    'semantic_cck_multiple_item_element', 'semantic_cck_multiple_item_class',
    'semantic_cck_use_singlevalue_settings', 'semantic_cck_single_item_element',
    'semantic_cck_single_item_class', 'semantic_cck_last_every_nth',
    'semantic_cck_first_class', 'semantic_cck_last_class',
    'semantic_cck_striping_classes');

  return $setting_names;
}

function semantic_cck_settings_form($field, $type) {
  if ($field['widget']['semantic_cck_use_semantic_instance']) {
    $settings = $field['widget'];
    $settings['semantic_cck_use_semantic_output'] = $field['semantic_cck_use_semantic_output'];
  }
  else {
    $settings = $field;
  }

  $form = array();

  $form['semantic_html_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Semantic HTML output'),
    '#collapsible' => TRUE,
    '#collapsed' => ($settings['semantic_cck_use_semantic_output']) ? FALSE : TRUE,
    '#weight' => 3,
    '#attributes' => array('class' => 'semantic-cck'),
  );
  $form['semantic_html_fieldset']['semantic_cck_field_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround the entire field with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will be the container for the entire field. Leave blank for no surrounding element.'),
    '#default_value' => isset($settings['semantic_cck_field_element']) ? $settings['semantic_cck_field_element'] : 'div',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['semantic_cck_field_class'] = array(
    '#type' => 'textfield',
    '#title' => t('Choose field element class(es)'),
    '#description' => t('The field element automatically gets field, field type and specific field classes (ie. <em>field field-type-text field-field-my-field-name</em>).'),
    '#default_value' => isset($settings['semantic_cck_field_class']) ? $settings['semantic_cck_field_class'] : '',
    '#required' => FALSE,
  );
  $form['semantic_html_fieldset']['label_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Field label'),
    '#description' => t('<strong>Please note that the placement or appearance of the label is still determined by the CCK !display_fields_settings.</strong>', array('!display_fields_settings' => l(t('Display fields settings'), 'admin/content/node-type/' . str_replace("_", "-", $type) . '/display'))),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => 'semantic-cck-labels'),
  );
  $form['semantic_html_fieldset']['label_fieldset']['above'] = array(
    '#type' => 'fieldset',
    '#title' => t('Labels above field value(s)'),
    '#description' => t('How to render the label when located above the field value(s).'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'semantic-cck-labels-above'),
  );
  $form['semantic_html_fieldset']['label_fieldset']['above']['semantic_cck_label_element_above'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround the label with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will surround the label.'),
    '#default_value' => ($settings['semantic_cck_label_element_above'] != '') ? $settings['semantic_cck_label_element_above'] : 'h3',
    '#required' => TRUE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['label_fieldset']['above']['semantic_cck_label_class_above'] = array(
    '#type' => 'textfield',
    '#title' => t('And a class of'),
    '#description' => t('The label automatically gets a class of <em>field-label</em>.'),
    '#default_value' => isset($settings['semantic_cck_label_class_above']) ? $settings['semantic_cck_label_class_above'] : '',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['label_fieldset']['above']['semantic_cck_label_suffix_above'] = array(
    '#type' => 'textfield',
    '#title' => t('And a suffix of'),
    '#description' => t('Insert the desired suffix character, eg. a colon'),
    '#default_value' => isset($settings['semantic_cck_label_suffix_above']) ? $settings['semantic_cck_label_suffix_above'] : '',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['label_fieldset']['inline'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inline labels'),
    '#description' => t('How to render the label when located inline with the field value(s).'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'semantic-cck-labels-inline'),
  );
  $form['semantic_html_fieldset']['label_fieldset']['inline']['semantic_cck_label_element_inline'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround the label with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will surround the label.'),
    '#default_value' => ($settings['semantic_cck_label_element_inline'] != '') ? $settings['semantic_cck_label_element_inline'] : 'span',
    '#required' => TRUE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['label_fieldset']['inline']['semantic_cck_label_class_inline'] = array(
    '#type' => 'textfield',
    '#title' => t('And a class of'),
    '#description' => t('The label automatically gets a class of <em>field-label-inline</em>.'),
    '#default_value' => isset($settings['semantic_cck_label_class_inline']) ? $settings['semantic_cck_label_class_inline'] : '',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['label_fieldset']['inline']['semantic_cck_label_suffix_inline'] = array(
    '#type' => 'textfield',
    '#title' => t('And a suffix of'),
    '#description' => t('Insert the desired suffix character, eg. a colon'),
    '#default_value' => isset($settings['semantic_cck_label_suffix_inline']) ? $settings['semantic_cck_label_suffix_inline'] : ':',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Field value(s)'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => 'semantic-cck-multiple-values'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue'] = array(
    '#type' => 'fieldset',
    '#title' => t('Multiple value field'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'field-values'),
    '#attributes' => array('class' => 'semantic-cck-multiple-values-all'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['items_element'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'semantic-cck-multiple-values-fields'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['items_element']['semantic_cck_multiple_items_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround all field values with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will be the container for all field values. Leave blank for no surrounding element.'),
    '#default_value' => isset($settings['semantic_cck_multiple_items_element']) ? $settings['semantic_cck_multiple_items_element'] : 'div',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['items_element']['semantic_cck_multiple_items_class'] = array(
    '#type' => 'textfield',
    '#title' => t('And a class of'),
    '#description' => t('The surrounding fields element automatically gets the <em>field-items</em> class.'),
    '#default_value' => isset($settings['semantic_cck_multiple_items_class']) ? $settings['semantic_cck_multiple_items_class'] : '',
    '#required' => FALSE,
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['item_element'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'semantic-cck-multiple-values-field'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['item_element']['semantic_cck_multiple_item_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround each field value with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will be the container for each field value. Leave blank for no surrounding element.'),
    '#default_value' => isset($settings['semantic_cck_multiple_item_element']) ? $settings['semantic_cck_multiple_item_element'] : 'div',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['multivalue']['item_element']['semantic_cck_multiple_item_class'] = array(
    '#type' => 'textfield',
    '#title' => t('And a class of'),
    '#description' => t('Each field instance automatically gets the <em>field-item</em> class. Insert a # where you want enumeration (ie field-item-#).'),
    '#default_value' => isset($settings['semantic_cck_multiple_item_class']) ? $settings['semantic_cck_multiple_item_class'] : '',
    '#required' => FALSE,
  );
  $form['semantic_html_fieldset']['items_fieldset']['singlevalue'] = array(
    '#type' => 'fieldset',
    '#title' => t('Single value field'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => 'semantic-cck-single-values-settings'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['singlevalue']['semantic_cck_use_singlevalue_settings'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use the following settings when the field contains only one value'),
    '#description' => t('Leave this unchecked to use multiple value field settings when the field contains only one value.'),
    '#return_value' => 1,
    '#default_value' => isset($settings['semantic_cck_use_singlevalue_settings']) ? $settings['semantic_cck_use_singlevalue_settings'] : 0,
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['singlevalue']['singlevalues'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => 'semantic-cck-single-values-item'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['singlevalue']['singlevalues']['semantic_cck_single_item_element'] = array(
    '#type' => 'textfield',
    '#title' => t('Surround field value with'),
    '#description' => t('Insert the desired <abbr title="Hyper Text Markup Language">HTML</abbr> element that will be the container for a single field value. Leave blank for no surrounding element.'),
    '#default_value' => isset($settings['semantic_cck_single_item_element']) ? $settings['semantic_cck_single_item_element'] : 'div',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['singlevalue']['singlevalues']['semantic_cck_single_item_class'] = array(
    '#type' => 'textfield',
    '#title' => t('And a class of'),
    '#default_value' => isset($settings['semantic_cck_single_item_class']) ? $settings['semantic_cck_single_item_class'] : '',
    '#description' => t('The field instance will automatically get a <em>field-item</em> class.'),
    '#required' => FALSE,
  );
  $form['semantic_html_fieldset']['items_fieldset']['nth_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('First and last classes'),
    '#description' => t('If the <em>FIRST/LAST every n<sup>th</sup></em> option is empty or zero, the <em>FIRST class attribute</em> and <em>LAST class attribute</em> are added once to only the first and last field values. If this option is greater than or equal to 1, these classe are added to every n<sup>th</sup> row, which may be useful for grid layouts where the initial and final unit\'s lateral margins must be 0.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => 'semantic-cck-nth-settings'),
  );
  $form['semantic_html_fieldset']['items_fieldset']['nth_fieldset']['semantic_cck_last_every_nth'] = array(
    '#type' => 'textfield',
    '#title' => t('FIRST/LAST every n<sup>th</sup>'),
    '#default_value' => is_numeric($settings['semantic_cck_last_every_nth']) ? $settings['semantic_cck_last_every_nth'] : '0',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['nth_fieldset']['semantic_cck_first_class'] = array(
    '#type' => 'textfield',
    '#title' => t('FIRST class attribute'),
    '#default_value' => isset($settings['semantic_cck_first_class']) ? $settings['semantic_cck_first_class'] : 'first',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['nth_fieldset']['semantic_cck_last_class'] = array(
    '#type' => 'textfield',
    '#title' => t('LAST class attribute'),
    '#default_value' => isset($settings['semantic_cck_last_class']) ? $settings['semantic_cck_last_class'] : 'last',
    '#required' => FALSE,
    '#size' => 20,
  );
  $form['semantic_html_fieldset']['items_fieldset']['semantic_cck_striping_classes'] = array(
    '#type' => 'textfield',
    '#title' => t('Striping class attributes'),
    '#description' => t('One striping class attribute is applied to each row. Separate multiple attributes with a space.'),
    '#default_value' => isset($settings['semantic_cck_striping_classes']) ? $settings['semantic_cck_striping_classes'] : 'odd even',
    '#required' => FALSE,
  );

  return $form;
}

function semantic_cck_form_alter(&$form, $form_state, $form_id) {
  // Add semantic HTML settings to the Global settings section of the field settings form
  if ($form_id == "content_field_edit_form" && isset($form['#field'])) {
    $type = content_types($form['type_name']['#value']);
    $field = $type['fields'][$form['field_name']['#value']];

    $additions = array();
    $additions['semantic_cck_use_semantic_output'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use semantic HTML for field output'),
      '#description' => t('Check this box to output the field using the semantic HTML settings below. Leave this box unchecked to use default CCK field output.'),
      '#return_value' => 1,
      '#default_value' => isset($field['semantic_cck_use_semantic_output']) ? $field['semantic_cck_use_semantic_output'] : 0,
      '#required' => FALSE,
      '#weight' => 1,
    );
    $additions['semantic_cck_use_semantic_instance'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use semantic HTML settings below for this instance only'),
      '#description' => t('Check this box to output the field using the semantic HTML settings below <strong>only for this instance of the field</strong>.'),
      '#return_value' => 1,
      '#default_value' => isset($field['widget']['semantic_cck_use_semantic_instance']) ? $field['widget']['semantic_cck_use_semantic_instance'] : 0,
      '#required' => FALSE,
      '#weight' => 2,
    );
    $additions = array_merge($additions, semantic_cck_settings_form($field, $form['type_name']['#value']));

    $form = array_merge($form, $additions);

    // Ensure that the submit button appears at the very bottom of the form
    $form['submit']['#weight'] = 10;

    drupal_add_css(drupal_get_path('module', 'semantic_cck') . '/theme/semantic_cck.css');
  }
}

function semantic_cck_widget_settings_alter(&$additions, $op, $field) {
  switch ($op) {
    case 'save':
      $setting_names = array(
        'semantic_cck_use_semantic_instance',
      );
      if ($field['semantic_cck_use_semantic_instance']) {
        $setting_names = array_merge($setting_names, _semantic_cck_setting_names());
      }
      $additions = array_merge($additions, $setting_names);
      break;
  }
}

function semantic_cck_field_settings_alter(&$additions, $op, &$field) {
  switch ($op) {
    case 'save':
      $setting_names = array(
        'semantic_cck_use_semantic_output',
      );

      $setting_names = array_merge($setting_names, _semantic_cck_setting_names());

      if ($field['semantic_cck_use_semantic_instance']) {
        // Preserve the old field settings
        $previous_field = unserialize($field['previous_field']);
        $semantic_cck_setting_names = _semantic_cck_setting_names();
        foreach ($semantic_cck_setting_names as $setting_name) {
          $field[$setting_name] = $previous_field[$setting_name];
        }
      }
      $additions = array_merge($additions, $setting_names);
      break;
  }
}

function semantic_cck_theme_registry_alter(&$theme_registry) {
  $theme_registry['content_field']['theme paths'][] = drupal_get_path('module', 'semantic_cck') . '/theme';
}

function semantic_cck_preprocess_content_field(&$variables) {
  $element = $variables['element'];
  $field = content_fields($element['#field_name'], $element['#node']->type);

  if (!$field['semantic_cck_use_semantic_output']) {
    return;
  }

  if ($field['widget']['semantic_cck_use_semantic_instance']) {
    $settings = $field['widget'];
  }
  else {
    $settings = $field;
  }

  // Provide semantic CCK field template suggestions
  $variables['template_files'][] = 'semantic-content-field';
  $variables['template_files'][] = 'semantic-content-field-' . $element['#field_name'];
  $variables['template_files'][] = 'semantic-content-field-' . $element['#node']->type;
  $variables['template_files'][] = 'semantic-content-field-' . $element['#field_name'] .'-' . $element['#node']->type;

  // Field
  $variables['field_element'] = $settings['semantic_cck_field_element'];
  $field_classes = array(
    'field',
    'field-type-' . $variables['field_type_css'],
    'field-' . $variables['field_name_css'],
    $settings['semantic_cck_field_class'],
  );
  $variables['field_attributes'] = array(
    'class' => trim(implode(' ', $field_classes)),
  );

  // Label
  $variables['label_element'] = ($variables['label_display'] == "above") ? $settings['semantic_cck_label_element_above'] : $settings['semantic_cck_label_element_inline'];
  $variables['label_class'] = ($variables['label_display'] == "above") ? $settings['semantic_cck_label_class_above'] : $settings['semantic_cck_label_class_inline'];
  $variables['label_suffix'] = ($variables['label_display'] == "above") ? $settings['semantic_cck_label_suffix_above'] : $settings['semantic_cck_label_suffix_inline'];

  // Items
  $num_items = count($variables['items']);
  if ($num_items == 1) {
    if (!$settings['semantic_cck_use_singlevalue_settings']) {
      $variables['items_element'] = $settings['semantic_cck_multiple_items_element'];
    }
    else {
      $variables['items_element'] = '';
    }
    $variables['items_attributes'] = array();
  }
  else {
    $variables['items_element'] = $settings['semantic_cck_multiple_items_element'];
    $items_classes = array('field-items', $settings['semantic_cck_multiple_items_class']);
    $variables['items_attributes'] = array(
      'class' => trim(implode(' ', $items_classes)),
    );
  }

  // Item
  if ($num_items == 1 && $settings['semantic_cck_use_singlevalue_settings']) {
    $variables['item_element'] = $settings['semantic_cck_single_item_element'];
  }
  else {
    $variables['item_element'] = $settings['semantic_cck_multiple_item_element'];
  }

  $last_every_nth = !empty($settings['semantic_cck_last_every_nth']) ? $settings['semantic_cck_last_every_nth'] : 0;
  $variables['item_attributes'] = array();
  foreach ($variables['items'] as $delta => $item) {
    $variables['item_attributes'][$delta] = array();

    $item_classes = array('field-item');
    if ($num_items == 1) {
      if ($settings['semantic_cck_use_singlevalue_settings'] && $settings['semantic_cck_single_item_class']) {
        $item_classes[] = $settings['semantic_cck_single_item_class'];
      }
      elseif (!$settings['semantic_cck_use_singlevalue_settings'] && $settings['semantic_cck_multiple_item_class']) {
        $item_classes[] = $settings['semantic_cck_multiple_item_class'];
      }
    }
    elseif ($num_items > 1) {
      if ($settings['semantic_cck_multiple_item_class']) {
        $item_classes[] = $settings['semantic_cck_multiple_item_class'];
      }
    }

    // Striping
    $striping_classes = array();
    if (trim($settings['semantic_cck_striping_classes'])) {
      $striping_classes = explode(' ', trim($settings['semantic_cck_striping_classes']));
      $item_classes[] = $striping_classes[$delta % count($striping_classes)];
    }

    if ($settings['semantic_cck_first_class']) {
      if (($last_every_nth && $delta % $last_every_nth == 0) || (!$last_every_nth && $delta == 0)) {
        $item_classes[] = $settings['semantic_cck_first_class'];
      }
    }
    if ($settings['semantic_cck_last_class']) {
      if (($last_every_nth && ($delta + 1) % $last_every_nth == 0) || (!$last_every_nth && ($delta + 1) == $num_items)) {
        $item_classes[] = $settings['semantic_cck_last_class'];
      }
    }

    $variables['item_attributes'][$delta]['class'] = str_replace('#', $delta, implode(' ', $item_classes));
  }
}