<?php

/* --- HOOKS ---------------------------------------------------------------- */

/**
 * Implementation of hook_menu().
 */
function empty_visit_log_menu() {
  $items = array();
  $items['admin/reports/settings/empty_visit_log'] = array(
    'title' => 'Empty visits access log',
    'description' => 'Empty advanced statistics logs.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('empty_visit_log_settings_form'),
    'access arguments' => array('empty visits access log'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/empty_visit_log'] = array(
    'title' => 'Empty visits access log',
    'description' => 'Empty advanced statistics logs.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('empty_visit_log_settings_form'),
    'access arguments' => array('empty visits access log'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Administration settings form.
 *
 * @see system_settings_form()
 */
function empty_visit_log_settings_form() {

  $form['resets']['reset_accesslog'] = array(
    '#type' => 'submit',
    '#value' => t('Clear access log'),
    '#submit' => array('empty_visit_log_reset_accesslog'),
  );
  $form['resets']['reset_counter'] = array(
    '#type' => 'submit',
    '#value' => t('Reset all node counters'),
    '#submit' => array('empty_visit_log_reset_counters'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_perm().
 */
function empty_visit_log_perm() {
  return array('empty visits access log');
}



/**
 * Resets the node view counter.
 */
function empty_visit_log_reset_counters() {
  db_query("DELETE FROM {node_counter}");
  drupal_set_message(t('Node counters reset.'));
}

/**
 * Clears the access log.
 */
function empty_visit_log_reset_accesslog() {
  db_query("DELETE FROM {accesslog}");
  drupal_set_message(t('Access log cleared.'));
}